### ISSUE TITLE
https 里面  写错了

### ISSUE THREAD

**Issue by y949548818** [heuuLZP/vue-axios#1]
写了两个then   ，第二个应该是catch 把

**Comment by heuuLZP** [comment]
@y949548818 第一个then里面执行checkStatus方法，第二个then里面执行checkCode方法，这里并没有写catch，如果你需要可以在最后面加上，而不是改变第二个then。

**Comment by y949548818** [comment]
@heuuLZP   明白了，没看清checkStatus 和checkCode。  谢谢教程 。^_^
