### ISSUE TITLE
请问，如果不想在每个页面中去判断是否成功在去执行操作，可以如下这样吗？

### ISSUE THREAD

**Issue by wendesun** [heuuLZP/vue-axios#5]
getData(){
           this.$axios.get("/h5/grammar/study/v3.0.0/list", {student_grunit_id: 1},  (data)=>{
               HT.log("【"+this.$options.name+"】", data)
           });
        },

-------------------------------------------
【http.js】
function checkCode (res, callback) {
    // 如果code异常(这里已经包括网络错误，服务器错误，后端抛出的错误)，可以弹出一个错误提示，告诉用户
    if (res.status === -404) {
        alert(res.msg)
    }
    if (res.data && (res.data.errcode != "200")) {
        alert(res.data.errmsg) ### //只提示错误，不执行操作
    }

    if (res.data && (res.data.errcode == "200")) {
        callback(res.data) //成功并执行回调函数
    }
}

**Comment by heuuLZP** [comment]
@wendesun 你好，实际上在页面中不判断也可以，如下图一所示：

![图一](https://user-images.githubusercontent.com/18410118/59207279-59119780-8bd9-11e9-8039-db16883e552b.png)
