### ISSUE TITLE
提点意见

### ISSUE THREAD

**Issue by Ricemonster** [heuuLZP/vue-axios#6]
![图片](https://user-images.githubusercontent.com/39476975/62275002-8eb55d00-b473-11e9-912e-b747af7974e3.png)
我这里返回的状态是 ok 所以你这段错误检测写的还不健壮
`if (res.data && (!res.data.success)) {
     alert(res.data.error_msg)
  }`
错误信息的判断也没有多少，只有一个网络错误

**Comment by heuuLZP** [comment]
@Ricemonster  你好，checkCode() 这个方法主要是为了处理后端返回的业务 code，这里需要您根据你的后端返回的数据结构自行设置的，每个公司或项目后端返回的数据结构也不可能完全一样。
